image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test
  - dockerize
  - deploy
   
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt


create_image:
  stage: dockerize
  image: docker:dind
  services:
    - docker:dind
  tags:
    - dind
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
   
deploy_image:
  stage: deploy
  image: $CI_REGISTRY/icc/kubectl:v1.19.10
  environment:
    name: k8.informatik.haw-hamburg.de
  script:
    - kubectl apply -f deploy.yaml

test:
  stage: test
  script:
    - coverage run --source=app -m unittest test/test_user.py
