apiVersion: apps/v1
kind: Deployment
metadata:
  name: haw-world
  namespace: project-se2
  labels:
    service: haw-world
spec:
  selector:
    matchLabels:
      service: haw-world
  template:
    metadata:
      labels:
        service: haw-world
    spec:
      containers:
        - image: git.haw-hamburg.de:5005/acf040/haw-world
          name: haw-world
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: Kws8DTzLfPzA-_e2rcz4
---
apiVersion: v1
kind: Service
metadata:
  name: haw-world
  namespace: project-se2
  labels:
    service: haw-world
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    service: haw-world
  type: ClusterIP
