apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-project-se2
  namespace: project-se2
  labels:
    service: be-project-se2
spec:
  selector:
    matchLabels:
      service: be-project-se2
  template:
    metadata:
      labels:
        service: be-project-se2
    spec:
      containers:
        - image: git.haw-hamburg.de:5005/se24/backend:latest
          name: be-project-se2
          ports:
            - containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: pull-secret-backend
---
apiVersion: v1
kind: Service
metadata:
  name: be-project-se2
  namespace: project-se2
  labels:
    service: be-project-se2
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    service: be-project-se2
  type: ClusterIP
