apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-se2-deploy
  namespace: project-se2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: be.taks.informatik.haw-hamburg.de
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: project-se2-serviceaccount
            port:
              number: 80
  tls: 
  - hosts:
    - be.taks.informatik.haw-hamburg.de
    secretName: ferdi1234