apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-se2-serviceaccount
  namespace: project-se2
subjects:
  - kind: ServiceAccount
    name: project-se2-serviceaccount
    namespace: project-se2
roleRef:
  kind: ClusterRole
  name: kiosk-space-admin
  apiGroup: rbac.authorization.k8s.io